osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v1.2.1/git-lfs-$([
  "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-1.2.1.tar.gz
  | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
- nvm install 10
- source ~/.bashrc
- npm install -g xvfb-maybe
script:
- npm install
- npm run build
branches:
  only:
  - master
# Only build tags
if: tag IS present
deploy:
  provider: releases
  api_key:
    secure: YjljsZoZqWB74XM48w75dA3KOCf+MLsBhio8XA6VUjFMtfdAbe371AyXkrFDPjYAtV+3IPFzwSMuL1EP8pldJdwg95AJB5SFO9dA3O3tkLcbZIZucY5kLg10Bzr/f/upbz4nJ5XhIGzH84TFG1+JuR0hA2BKGHXQMBgildLHZcjZfrRUoSts0oHdh6ldGmiwCYrBeyuH0pQlXjP5IhOY0jXzuZeqlVlpE9sboBEnSTkJDKR8RxHY7PwhLO53OgId044XAar+t2dhtEmMmTFPyECive8saXKccbBLRsh6aqcTcN7Ue4bPr3pHacsTf1d2rPkvatmkA2seWTQyOIrscXXXsEBfsEM6+Xy3inX6xEn/kQ1B7bQdL34zKyjJ8XywzVmjp3xkgRxsy6VEaHPxc5Z5erfNZUD5MgaCmYv8URR81xEV6yk7w+TWS47NV8oTJcRzsswkEzvSx7SMlcq7YKVKObFdqCEup/L1Ap1uPb4lQsQTgrzzHvYOBYYdE7q2YFjotj1UPmOKofD6jxX+i7CNxwJ7QQS76N8bvey4ZnKgvRhaBaOdAzv4uAcSJtEXR6B4Ize+7ZA4x25Rl3ee/zYuQFp7EU2OxuYoOYMFFxWbt430rdaUTYVypYuK5SlcS5VxB+VxSKAc8wb9aSFJKryfESnRWjpJAfPp9didUn4=
  file_glob: true
  file:
  - build/apocaloops *.AppImage
  - build/apocaloops-*-mac.zip
  skip_cleanup: true
  on:
    repo: PatrickStephansen/apocaloops
    branch: master
    tags: true
