skip_non_tags: true

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - git reset --hard HEAD
  - node --version
  - npm install

build_script:
  - npm run build
  - ls ./build

test: off

artifacts:
  - path: 'build\apocaloops *.exe'
    name: 'Windows executable'

deploy:
  release: $(appveyor_repo_tag_name)
  description: 'Add different options for what to do when a sample ends. Add radio mode to overlap behaviour options. Radio mode behaves as if all the samples are always playing, and selecting one tunes in to that station.'
  provider: GitHub
  auth_token:
    secure: ipKyqhOAwoaDWKmffCB20kyRzDQpQueR5VmA18JkDSQOmLZnbc10DaGUjFGKTcCA
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true